### ISSUE TITLE
Rich Presence

### ISSUE THREAD

**Issue by JotaroKjo** [Solar-Tweaks/SolarPatcher#1]
Hello, I was wondering if it was possible to replace the "Playing on Private Server" by the IP of the server on which we are ?

**Comment by 770grappenmaker** [comment]
I would say that this could pose some security issues; it would mean that you would broadcast the IP address to anyone that can see your profile. I can understand the request if you are on a smaller public server, or if you do not care about people knowing about your server address, so I could implement a switch to allow unknown servers, or allow to map your own server names. Tell me which one you would prefer.

**Comment by dtomvan** [comment]
You could look for strings in the server IP, to know if the server is an SMP and thus doesn't dox anything. For example: aternos.me, minehut.gg

**Comment by JotaroKjo** [comment]
> 

I think it's better to map server name if it's possible. Ty for your answer !

**Comment by 770grappenmaker** [comment]
Ok, I'll implement this. Thanks for the suggestion!

**Comment by 770grappenmaker** [comment]
Main branch now has the feature. Add a `customServerMappings` entry to the `RPCUpdate` module in your config, it'll look like this:

```json
{
    "rpcUpdate": {
        "customServerMappings": {
            "localhost": "My Local Server"
        }
    }
}
```

Do note that the IP address must EXACTLY match, so if you are on `localhost:25565`, that will not match.  
Thanks for your contribution!

**Comment by 770grappenmaker** [comment]
> You could look for strings in the server IP, to know if the server is an SMP and thus doesn't dox anything. For example: aternos.me, minehut.gg

In my opinion, this still allows for accidentally doxing your (private) SMP, and this is about SMPs only, which already exist in the official server [mappings](https://github.com/LunarClient/ServerMappings).  
@dtomvan

**Comment by dtomvan** [comment]
With 142 contributors the server mappings are the first thing Lunar made open-source :rofl:
