### ISSUE TITLE
It doesn't tweak with the new lunar update

### ISSUE THREAD

**Issue by bestdeveloperforever** [Solar-Tweaks/SolarPatcher#11]
**Describe the bug**
It doesn't tweak with the new lunar update

**To Reproduce**

**Expected behavior**
It doesn't tweak with the new lunar update

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher ALL
 - Version 1.6.1
 - Lunar Version 4a6937e

**Additional context**
Add any other context about the problem here. If applicable, attach (parts of) stacktraces and errors, config files etc.

**Comment by 770grappenmaker** [comment]
Known issue, please fill in the issue template next time. The thing is, it does apply patches just not the metadata ones (blog post, freelook etc). Don't really have time right now so please stand by and be patient.

**Comment by 770grappenmaker** [comment]
Closed by c154ea39006e936b1bd779f4eef657ef6e1fb355
