### ISSUE TITLE
Solar Tweaks prblems

### ISSUE THREAD

**Issue by oCiph3r** [Solar-Tweaks/SolarPatcher#13]
how do u install this? 
bsaically i think my solar tweaks is broken 
i cant launch any version except 1.8 or 1.7 whenever i launch anything except those (e.g 1.18 or 1.16) soalrtweaks just closes and does nothing else
also when i launch 1.7 and 1.8 it says an error
'Config appears to be invalid - please fix configuration issues (e.g. numerical values) or delete your config to fallback to default'
^ this error comes up 
i didnt touch the jvm arguments i resintalled solar tweask btu nothing works for some reason
i need a fix for this lol
also fuunny thin whnever i launch 1.7 and 1.8 the error comes up but when i launch anything else it just traight up doesnt show an error or luncht the game
but 1.8 and 1.7 i get the error and press ok but then the game still launches
ALSO is 1.8 nohitreg still working? for me it doesnt work
how do u update solar tweaks btw and use solarpatcher whatever it is i though solarpatcher was an updater thingy

**Comment by 25huizengek1** [comment]
This is related to the launcher, not the solarpatcher

**Comment by 770grappenmaker** [comment]
Duplicate
