### ISSUE TITLE
Uncapped Reach not working

### ISSUE THREAD

**Issue by ZakonP** [Solar-Tweaks/SolarPatcher#14]
**Describe the bug**
I am using 4 block reach and when i get a 4 block hit it shows 3 blocks (the capped)

**Expected behavior**
I expected it to show the accurate and uncapped reach.

**Screenshots**
![image](https://user-images.githubusercontent.com/107328268/173208321-3ebc7a2f-cd2d-4817-862e-8e6a15e37204.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Launcher: Solar Tweaks
 - Version: 1.7
 - Lunar Version: 4a6937e

**Comment by 770grappenmaker** [comment]
That might mean the module broke with a new update. Can you share logs as described by the patcher wiki?

**Comment by Dynvsty** [comment]
just don't hack 💀

**Comment by 770grappenmaker** [comment]
Um, in creative mode you can reach 4 blocks. Also the reach calculation is a bit messed up. If you stand one block under an entity, lunar will tell you you are reaching 3.0 blocks when in reality it is only one block. That is why this module exists. Lunar basically takes the distance between your feet and your opponents feet, but that is only valid if both players are on equal elevation.
