### ISSUE TITLE
Server to join

### ISSUE THREAD

**Issue by KBCats** [Solar-Tweaks/SolarPatcher#19]
Trying to go on hypixel.net or hypixel.net:25565

What url is it?

**Comment by 770grappenmaker** [comment]
The way to join the Hypixel Network through a Minecraft client is carefully documented by the Hypixel Development Team. The relevant information can be found over at [their site](https://hypixel.net/play/). A summary: the Internet Protocol (DNS-resolved) address/domain name to join the official Hypixel Network is, in fact, `mc.hypixel.net`. Have a great day.

**Comment by KBCats** [comment]
> The way to join the Hypixel Network through a Minecraft client is carefully documented by the Hypixel Development Team. The relevant information can be found over at [their site](https://hypixel.net/play/). A summary: the Internet Protocol (DNS-resolved) address/domain name to join the official Hypixel Network is, in fact, `mc.hypixel.net`. Have a great day.

bro..

**Comment by 770grappenmaker** [comment]
Dumb question, dumb answer. What do you want? Please elaborate

**Comment by KBCats** [comment]
> Dumb question, dumb answer. What do you want? Please elaborate

After running non run start or the exe it does say proxy started but never shows anything for the microsoft auth/command in game

**Comment by 770grappenmaker** [comment]
This is not solar patcher related. Closing because of lack of relevance
