### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by VytskaLT** [Solar-Tweaks/SolarPatcher#2]
I was looking around the source code and saw that the tasklist and hostlist modules use Windows paths:
![image](https://user-images.githubusercontent.com/35194709/163434877-769edbc0-d72d-4006-aa46-c7cd29ecdee2.png)
Does Lunar also have this spyware for Linux machines? If so, it would be great if support for it was added to this module too.

**Comment by RadNotRed** [comment]
Lunar probably doesn't care for linux as much. But maybe in the future,

**Comment by 770grappenmaker** [comment]
As far as I am aware, after debugging the socket on an arch box, there is no packet sending your task and host lists, it is windows only. If I do find anything I will add support.

**Comment by 770grappenmaker** [comment]
Couldn't find anything, so I will close this for now, but do not hesitate to come back when you do find something (or i'll reopen when i find something)
