### ISSUE TITLE
Stuck on "Checking LC Assets..."

### ISSUE THREAD

**Issue by ambiennt** [Solar-Tweaks/SolarPatcher#21]
**The bug:**
Every so often, launching Solar Tweaks gets stuck on the launch phase. Specifically it always halts on the "Checking LC Assets..." message. Launching with the official Lunar launcher, closing, then immediately launching with solar tweaks seems to resolve the issue, but only temporarily. The fix for this might somehow be user error and/or trivial to fix but regardless I thought it might be useful for anyone else having the problem to help them diagnose.

**Steps to reproduce the behavior:**
1. Go to the solar tweaks launcher
2. Click on the big green launch button
3. Notice that the launcher gets stuck on launch unless you have very recently launched with the official Lunar launcher

**Expected behavior:**
I expect the Solar tweaks launcher to be able to launch as the official Lunar launcher would.

Image depicting the bug:
![image](https://user-images.githubusercontent.com/63216972/188075505-2dae31ec-00f2-4df6-b57c-ffc397e33a45.png)

**Additional info:**
 - OS: Windows 10 19044.1706
 - Launcher: https://github.com/Solar-Tweaks/SolarPatcher/releases/tag/v1.7.2
 - Version 1.7.2 pre release (latest at the time of writing), launcher version 4.0.4 (according to the "about" tab of the Solar Tweaks launcher)
 - Lunar Version: v2.12.7 (according to the "about" tab of the official Lunar launcher)
- tested issue on launching Minecraft v1.7.10
- i use graalvm-ce-java17-22.1.0 as my JRE with graalvm community JVM preset args from the Solar Tweaks launcher

**Comment by 770grappenmaker** [comment]
unrelated to solar patcher

**Comment by ambiennt** [comment]
Care to elaborate?
