### ISSUE TITLE
[Feature Request] Discord RPC Icon for every server

### ISSUE THREAD

**Issue by Zone-Infinity** [Solar-Tweaks/SolarPatcher#5]
Only Client logo on the large icon is boring
We can have server icon on the small icon :D
or vice versa (server on large, client on small)

If the server icon isn't there in the assets , it will be just the Client logo.

**Comment by 770grappenmaker** [comment]
I like the idea, but the problem is, unless we would pre-specify some icons for hypixel and known servers on the discord application, it won't work. How would you like it to work? Server ip gets used as asset name, so if you upload that asset yourself it will show?

**Comment by 25huizengek1** [comment]
The only way that will work is (according to the Discord RPC docs) to upload the sever icon to the Discord media proxy (media.discordapp.net) and prefix the image id with `mp:`

**Comment by 770grappenmaker** [comment]
Could also work, though im not sure if you can just upload things to the media proxy

**Comment by Zone-Infinity** [comment]
> The only way that will work is (according to the Discord RPC docs) to upload the sever icon to the Discord media proxy (media.discordapp.net) and prefix the image id with `mp:`

Can u link me to that docs ?

**Comment by Zone-Infinity** [comment]
> The only way that will work is (according to the Discord RPC docs) to upload the sever icon to the Discord media proxy (media.discordapp.net) and prefix the image id with `mp:`

This can be done : [Docs](https://discord.com/developers/docs/topics/gateway#activity-object-activity-asset-image)

**Comment by 770grappenmaker** [comment]
I can try uploading all server icons in the lunar client server mappings to our discord application, that should work and doesnt require the slow option of reuploading etc.

**Comment by 770grappenmaker** [comment]
I just implemented it, I will push it soon. (Tell me if you want it now, then I'll release it, or if you're willing to wait for the feature)

**Comment by 770grappenmaker** [comment]
![image](https://user-images.githubusercontent.com/50543283/165507250-c6251ccc-7296-486f-88e6-8252c120ca87.png)
(By the way this is what it looks like)

**Comment by Zone-Infinity** [comment]
that's pog

**Comment by Zone-Infinity** [comment]
willing to wait for the feature ^

**Comment by Zone-Infinity** [comment]
I guess we should not close issue unless it's in the release , right ?

**Comment by 770grappenmaker** [comment]
Hm, I'll release soon, but fair, it is not yet "resolved".

**Comment by 770grappenmaker** [comment]
Whoops, didn't close
