### ISSUE TITLE
[REPOST] lc-qt SolarPatcher crash

### ISSUE THREAD

**Issue by simplictyy** [Solar-Tweaks/SolarPatcher#8]
https://github.com/orgs/Solar-Tweaks/discussions/161

so i tried to launch lcqt with solar patcher (it launches, freezes, doesnt respond, and proceed to launch)
[image](https://user-images.githubusercontent.com/71561421/167880297-35ac531a-4750-4102-9681-14251b1c6201.png)
it worked and managed to launch
some parts of the patcher works (as you can see the window name works)

but some parts of the patcher also isnt working like pinned servers and blog posts, lunar options etc.
[image](https://user-images.githubusercontent.com/71561421/167880724-083b2abd-5521-4ed7-8896-cfb31e74cd07.png)
[image](https://user-images.githubusercontent.com/71561421/167881126-416fe812-005b-4e38-bcaa-20c3b5d489a7.png)
[image](https://user-images.githubusercontent.com/71561421/167881203-ddaf700a-fad3-4aed-ad0f-64be9d44e933.png)

now, im wondering how do you customize the text, spoofing, values, etc. of the patcher?
i read that you need to create a file named config.json and then proceed to add this text:
-javaagent:/path/to/solar-patcher.jar=/path/to/config.json
to the jvm arguments of the launcher

but when i do add the jvm argument my launcher closes, and doesnt actually launch lunar or minecraft

also, another question how do you enable a mod with the config.json?
do i type true in these slots or do i have to type something else?

[image](https://user-images.githubusercontent.com/71561421/167882802-21d520cd-4284-465f-bac2-e0636ecd0faa.png)
[image](https://user-images.githubusercontent.com/71561421/167882863-bed95c9b-d3a4-417b-9e8d-b9d24d1f927b.png)

another thing to mention i tried to change the jvm argument abit from
this:
-javaagent:/path/to/solar-patcher.jar=/path/to/config.json
to this
-javaagent:C:\Users(name)\Downloads/solar-patcher.jar=C:\Users(name)\Desktop/config.json
but it also didnt work.
![image](https://user-images.githubusercontent.com/71561421/168000160-10c9a0e3-5f90-4d1e-af77-10ff7ea76a1a.png)

hey, a follow up to the thing i just said i realized the name of the .jar isnt the same as the one in the jvm argument i changed it and it launched
but it didnt change the windows title of minecraft/lunar and after abit of waiting it crashed and gave me a crash report but it immedietely closed and went back to the launcher.
https://user-images.githubusercontent.com/71561421/167884790-d07712b0-d029-47a1-a248-dae1e7d61042.png

picture of it launching:
https://user-images.githubusercontent.com/71561421/167885778-931ede15-4ed4-4d2c-8e68-18f26ef68208.png

picture of it crashing:
https://user-images.githubusercontent.com/71561421/167885902-518de0f0-2c1e-4808-a241-333c2fa882ca.png

**Comment by simplictyy** [comment]
look at my post at discussion (top link), the embeds actually work and the stuff makes more sense

**Comment by 770grappenmaker** [comment]
Okay so, what is most likely happening is that your config sets some values which are somewhat invalid, as in, break the bytecode. Please attach full logs (logs of stdout, not game logs) and your config. Empty pictures of launch and crash aren't helpful.

**Comment by 770grappenmaker** [comment]
To enable a mod in config.json simply set "isEnabled" in the config to true

**Comment by simplictyy** [comment]
> Okay so, what is most likely happening is that your config sets some values which are somewhat invalid, as in, break the bytecode. Please attach full logs (logs of stdout, not game logs) and your config. Empty pictures of launch and crash aren't helpful.

how do i get my stdout logs 

my config is only this
`{
    "windowName": {
        "from": "Lunar Client (\u0001-\u0001/\u0001)",
        "to": "TESTING",
        "isEnabled": true
    }
}`

**Comment by simplictyy** [comment]
![image](https://user-images.githubusercontent.com/71561421/168052701-5b92f86c-ee48-4581-84de-8ff818bc537a.png)
what it looks like in notepad

**Comment by simplictyy** [comment]
i also tested out ur configexample.json as it is but it also did the same stuff (launches minecraft, doesnt respond, crash)
i also tested out this but it also did the same thing (launches minecraft, doesnt respond, crash)
![image](https://user-images.githubusercontent.com/71561421/168054588-dc53df25-a14e-4116-a3c0-e6116ec65718.png)

**Comment by 770grappenmaker** [comment]
I don't think that is a valid config. Also keep in mind that solar patcher sometimes doesnt work with other agents. Try using a valid config instead, and alter that: https://github.com/Solar-Tweaks/SolarPatcher/blob/main/config.example.json

Launching with lcqt is also not recommended since the agents it has could cause side effecr because they get loaded earlier

**Comment by 770grappenmaker** [comment]
For sending logs, lcqt has terrible debugging capabilities so you cannot really see the logs afaik

**Comment by simplictyy** [comment]
i didnt have any other agents on it was just solar patcher,
ill try using the config that u sent and ill alter it ill tell u if it works or not

**Comment by simplictyy** [comment]
i tried to launch it but it did the same stuff again, opens minecraft, doesnt respond, and closes
what other launchers can i use to use solar patcher other than solartweaks itself?
